apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
  namespace: image-factory
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${registry_storage_class:-single}
  resources:
    requests:
      storage: ${registry_storage_size:-10Gi}
