apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harbor-image-factory-auth
  namespace: provisioning
subjects:
  - kind: ServiceAccount
    name: harbor-image-factory-auth
    namespace: registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: harbor-image-factory-auth
