apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: omni-kube-proxy
  namespace: omni
spec:
  secretName: omni-kube-proxy-tls
  issuerRef:
    name: ${omni_cert_issuer}
    kind: ClusterIssuer
  dnsNames:
    - ${omni_kube_proxy_hostname}
