apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: patches/helm-release.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: image-factory
      namespace: image-factory
