---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: siderolabs
  namespace: provisioning
spec:
  interval: 10m
  timeout: 3m
  type: oci
  url: oci://ghcr.io/siderolabs/charts
