#!/usr/bin/env bash
# Vendor CRDs into kustomize/crds/<name>-<version>/ from the central manifest
# (kustomize/crds/sources.yaml). Each listed entry is (re)generated — its CRD file
# and its kustomization.yaml, with any stray file inside that dir removed. A vendor
# dir not in the manifest (a superseded version) is deleted on regenerate, or flagged
# as drift in --check mode — it is never left behind: nothing keeps applying it once
# no entry in the manifest points at it, and the crds: layer's prune:false means the
# already-applied CRD objects are unaffected either way. Update sources.yaml first if
# you're mid-way through hand-adding a new vendor, or its unfinished dir gets deleted.
#
#   scripts/vendor-crds.sh          regenerate everything, delete superseded dirs
#   scripts/vendor-crds.sh --check  verify everything matches; non-zero on drift (CI)
#
# Per entry: name + version derive the dir/file; source is url | helm mode:crds |
# helm mode:template. In url, ${version} is interpolated.

set -euo pipefail

MANIFEST="kustomize/crds/sources.yaml"
CRDS_DIR="kustomize/crds"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

[ -f "$MANIFEST" ] || { echo "manifest not found: $MANIFEST" >&2; exit 1; }

# Clean up the per-iteration temp files on any exit path — set -euo pipefail aborts
# mid-generate (e.g. a curl/helm failure) after mktemp has already run.
trap 'rm -f "${crd_tmp:-}" "${kust_tmp:-}" "${root_tmp:-}" 2>/dev/null' EXIT

# generate_crds <index> <version> -> CRD yaml on stdout
generate_crds() {
  local i="$1" version="$2" url helm_chart
  url=$(yq ".vendors[$i].url // \"\"" "$MANIFEST")
  helm_chart=$(yq ".vendors[$i].helm.chart // \"\"" "$MANIFEST")

  if [ -n "$url" ]; then
    # '${version}' is the literal placeholder in the manifest URL, matched and
    # replaced with the resolved version — the single quotes are intentional.
    # shellcheck disable=SC2016
    url=${url//'${version}'/$version}
    curl -fsSL "$url"
    return
  fi

  if [ -n "$helm_chart" ]; then
    local repo mode
    repo=$(yq ".vendors[$i].helm.repo" "$MANIFEST")
    mode=$(yq ".vendors[$i].helm.mode // \"crds\"" "$MANIFEST")

    if [ "$mode" = "crds" ]; then
      helm show crds "$helm_chart" --repo "$repo" --version "$version"
    else
      local set_args=()
      while IFS= read -r s; do
        [ -n "$s" ] && set_args+=(--set "$s")
      done < <(yq ".vendors[$i].helm.set // [] | .[]" "$MANIFEST")
      # ${arr[@]+...} guards empty-array expansion under bash 3.2 + set -u.
      helm template crds "$helm_chart" --repo "$repo" --version "$version" --include-crds \
        ${set_args[@]+"${set_args[@]}"} \
        | yq 'select(.kind == "CustomResourceDefinition")
              | del(.metadata.labels."app.kubernetes.io/managed-by")
              | del(.metadata.labels."helm.sh/chart")
              | del(.metadata.annotations."meta.helm.sh/release-name")
              | del(.metadata.annotations."meta.helm.sh/release-namespace")'
    fi
    return
  fi

  echo "vendor[$i] declares neither url nor helm" >&2
  return 1
}

# kustomization_yaml <file> -> generated component wrapper on stdout. Each vendor
# dir is a kustomize Component: the synthesized `crds` layer overlays them onto the
# crds/ base, and entries under `components:` must be kind: Component.
kustomization_yaml() {
  printf '# Generated by task crds from kustomize/crds/sources.yaml — do not edit.\n'
  printf 'apiVersion: kustomize.config.k8s.io/v1alpha1\n'
  printf 'kind: Component\n'
  printf 'resources:\n'
  printf '  - %s\n' "$1"
}

# root_base_yaml -> inert base for kustomize/crds/ on stdout. The CLI's synthesized
# `crds` layer accumulates this dir as its base, then overlays each vendor as a
# component, so the dir needs a non-empty kustomization (an empty/missing one fails
# `kustomize build`). kind: Kustomization keeps it out of isKustomizeComponent().
root_base_yaml() {
  printf '# Generated by task crds from kustomize/crds/sources.yaml — do not edit.\n'
  printf '# Inert base for the synthesized crds: layer; vendor dirs attach as components.\n'
  printf 'apiVersion: kustomize.config.k8s.io/v1beta1\n'
  printf 'kind: Kustomization\n'
  printf 'resources: []\n'
}

count=$(yq '.vendors | length' "$MANIFEST")
drift=0
expected_dirs=""

i=0
while [ "$i" -lt "$count" ]; do
  name=$(yq ".vendors[$i].name" "$MANIFEST")
  version=$(yq ".vendors[$i].version" "$MANIFEST")
  dir="$name-$version"
  file="$name-$version.yaml"
  expected_dirs="$expected_dirs $dir"

  vdir="$CRDS_DIR/$dir"
  crd_out="$vdir/$file"
  kust_out="$vdir/kustomization.yaml"
  crd_tmp=$(mktemp)
  kust_tmp=$(mktemp)

  generate_crds "$i" "$version" > "$crd_tmp"
  kustomization_yaml "$file" > "$kust_tmp"

  if [ "$CHECK" = "1" ]; then
    for pair in "$crd_out|$crd_tmp" "$kust_out|$kust_tmp"; do
      out="${pair%%|*}"; tmp="${pair##*|}"
      if diff -q "$out" "$tmp" >/dev/null 2>&1; then
        echo "ok    $out"
      else
        echo "DRIFT $out"
        drift=1
      fi
    done
    # stray files in the dir (e.g. a pre-rename CRD file) are drift too
    if [ -d "$vdir" ]; then
      while IFS= read -r extra; do
        [ -z "$extra" ] && continue
        echo "EXTRA $extra"
        drift=1
      done < <(find "$vdir" -maxdepth 1 -type f ! -name "$file" ! -name kustomization.yaml)
    fi
  else
    mkdir -p "$vdir"
    mv "$crd_tmp" "$crd_out"
    mv "$kust_tmp" "$kust_out"
    # drop anything else in the dir so its contents are exactly the manifest's
    find "$vdir" -maxdepth 1 -type f ! -name "$file" ! -name kustomization.yaml -delete
    echo "wrote $vdir/"
  fi
  rm -f "$crd_tmp" "$kust_tmp"
  i=$((i + 1))
done

# Root base for the synthesized crds: layer.
root_out="$CRDS_DIR/kustomization.yaml"
root_tmp=$(mktemp)
root_base_yaml > "$root_tmp"
if [ "$CHECK" = "1" ]; then
  if diff -q "$root_out" "$root_tmp" >/dev/null 2>&1; then
    echo "ok    $root_out"
  else
    echo "DRIFT $root_out"
    drift=1
  fi
else
  mv "$root_tmp" "$root_out"
  echo "wrote $root_out"
fi
rm -f "$root_tmp"

# A vendor dir not in the manifest is a superseded version. Deleted on regenerate
# (nothing will ever apply it again once sources.yaml stops pointing at it, and the
# crds: layer's prune:false leaves already-applied CRD objects untouched regardless);
# flagged as drift in --check mode instead, so CI fails until someone runs
# 'task crds' and commits the result.
while IFS= read -r d; do
  [ -z "$d" ] && continue
  name=$(basename "$d")
  case " $expected_dirs " in
    *" $name "*) ;;
    *)
      if [ "$CHECK" = "1" ]; then
        echo "DRIFT $d not in manifest (stale — run 'task crds')"
        drift=1
      else
        rm -rf "$d"
        echo "removed $d (superseded — not in manifest)"
      fi
      ;;
  esac
done < <(find "$CRDS_DIR" -mindepth 1 -maxdepth 1 -type d | sort)

if [ "$CHECK" = "1" ] && [ "$drift" = "1" ]; then
  echo "CRD drift detected — run 'task crds' and commit the result." >&2
  exit 1
fi
echo "Done."
